Traceback (most recent call last):
  File "C:\Users\sungmooklim\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\sungmooklim\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\sungmooklim\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\sungmooklim\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\sungmooklim\anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\sungmooklim\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\sungmooklim\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\sungmooklim\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#np.where 
skimming_data2['group'] = np.where(skimming_data2['skimm'].between(4,6),'4~6',
                                  np.where(skimming_data2['skimm'].between(6,10),'7~10', '10~'))
# inullë¡œ np where 
total_data['edge_crack'] = np.where(total_data['HFI ë¹„ê³ '].isnull(),0,1)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [9][0m, in [0;36m<cell line: 2>[1;34m()[0m
[0;32m      1[0m [38;5;66;03m#np.where [39;00m
[1;32m----> 2[0m skimming_data2[[38;5;124m'[39m[38;5;124mgroup[39m[38;5;124m'[39m] [38;5;241m=[39m np[38;5;241m.[39mwhere([43mskimming_data2[49m[[38;5;124m'[39m[38;5;124mskimm[39m[38;5;124m'[39m][38;5;241m.[39mbetween([38;5;241m4[39m,[38;5;241m6[39m),[38;5;124m'[39m[38;5;124m4~6[39m[38;5;124m'[39m,
[0;32m      3[0m                                   np[38;5;241m.[39mwhere(skimming_data2[[38;5;124m'[39m[38;5;124mskimm[39m[38;5;124m'[39m][38;5;241m.[39mbetween([38;5;241m6[39m,[38;5;241m10[39m),[38;5;124m'[39m[38;5;124m7~10[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m10~[39m[38;5;124m'[39m))
[0;32m      4[0m [38;5;66;03m# inullë¡œ np where [39;00m
[0;32m      5[0m total_data[[38;5;124m'[39m[38;5;124medge_crack[39m[38;5;124m'[39m] [38;5;241m=[39m np[38;5;241m.[39mwhere(total_data[[38;5;124m'[39m[38;5;124mHFI ë¹„ê³ [39m[38;5;124m'[39m][38;5;241m.[39misnull(),[38;5;241m0[39m,[38;5;241m1[39m)

[1;31mNameError[0m: name 'skimming_data2' is not defined
NameError: name 'skimming_data2' is not defined

